name: Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: |
          brew install cmake libgit2

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -GXcode -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: VersionTools-macOS
          path: build/bin/VersionTools.app
          retention-days: 7

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            git \
            libgit2-dev \
            qt6-base-dev \
            qt6-tools-dev \
            qt6-l10n-tools

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          ninja

      - name: Create DEB package
        run: |
          cd build
          cpack -G DEB

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: VersionTools-Linux
          path: build/bin/VersionTools
          retention-days: 7

      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: VersionTools-Linux-DEB
          path: build/*.deb
          retention-days: 7

  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: VersionTools-Windows
          path: build/bin/Release/VersionTools.exe
          retention-days: 7

  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format cppcheck

      - name: Check code formatting
        run: |
          find src -name "*.cpp" -o -name "*.h" | xargs clang-format --dry-run --Werror || true

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --suppress=missingIncludeSystem src/core/ || true
